#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

#
# manta-triggers-show: show triggers and trigger-related procedures on the
# "manta" Moray bucket.
#

#
# LIBMANTA_POSTGRES_HOST should denote an IP address or DNS name of a primary
# Manatee peer.
#
if [[ -z "$LIBMANTA_POSTGRES_HOST" ]]; then
	echo "LIBMANTA_POSTGRES_HOST must be set in the environment."
	exit 2
fi

psql -h "$LIBMANTA_POSTGRES_HOST" -U moray moray <<EOF
SELECT event_manipulation as event,
       trigger_name,
       event_object_table as table,
       action_statement
    FROM information_schema.triggers
    WHERE event_object_table = 'manta';

SELECT proname
    FROM pg_proc
    WHERE proname like 'count_manta_%';
EOF
